### ISSUE TITLE
[Green Check Error] Space Paranoids - Communications Tower

### ISSUE THREAD

**Issue by superfid2006** [JDProchaska/Kingdom-Hearts-2-FM-Pop-Tracker-Pack#4]
Hello, decided to follow your advice and post issues on here instead of the discord.

As can be seen in the image below, the Communications Room I/O Tower Map icon is left green despite gathering it.
![image](https://github.com/JDProchaska/Kingdom-Hearts-2-FM-Pop-Tracker-Pack/assets/118657073/af228bcf-9743-4e97-a74e-56556e34c246)

**Comment by JDProchaska** [comment]
Thanks for the heads up! I will add this to the list of fixes coming in the next update.

**Comment by JDProchaska** [comment]
Fixed with #8
